# Generated by Django 5.1.1 on 2024-09-25 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250, verbose_name='Тема рассылки')),
                ('body', models.TextField(verbose_name='Текст рассылки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание рассылки')),
                ('periodicity', models.CharField(choices=[('once', 'Однократно'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('yearly', 'ежегодно')], max_length=50, verbose_name='Периодичность')),
                ('start_from', models.DateTimeField(verbose_name='Дата начала отправки')),
                ('stop_at', models.DateTimeField(verbose_name='Дата окончания отправки')),
                ('status', models.CharField(choices=[('create', 'Создана'), ('launched', 'Запущена'), ('completed', 'Завершена')], default='create', max_length=50, verbose_name='Статус рассылки')),
                ('client', models.ManyToManyField(to='mailing.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'настройка рассылки',
                'verbose_name_plural': 'настройки рассылок',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('status', models.BooleanField(verbose_name='статус попытки')),
                ('server_response', models.CharField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='клиент рассылки')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.emailsetting', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
