# Generated by Django 5.1.1 on 2024-09-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_emailsetting_mailinglog_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsetting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
    ]
