# Generated by Django 5.1.1 on 2024-09-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_client_patronymic_alter_emailsetting_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglog',
            options={},
        ),
        migrations.AlterField(
            model_name='emailsetting',
            name='periodicity',
            field=models.CharField(choices=[('Однократно', 'Однократно'), ('Ежедневно', 'Ежедневно'), ('Еженедельно', 'Еженедельно'), ('Ежемесячно', 'Ежемесячно'), ('Ежегодно', 'ежегодно')], max_length=50, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='emailsetting',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена'), ('Неудачная попытка', 'Неудачная попытка')], default='create', max_length=50, verbose_name='Статус рассылки'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='status',
            field=models.BooleanField(default=False, verbose_name='статус попытки'),
        ),
    ]
