# Generated by Django 5.1.1 on 2024-10-07 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailinglog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsetting',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена'), ('Неудачная попытка', 'Неудачная попытка')], default='Создана', max_length=50, verbose_name='Статус рассылки'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mailing.client', verbose_name='клиент рассылки'),
        ),
        migrations.AlterField(
            model_name='mailinglog',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailing.emailsetting', verbose_name='рассылка'),
        ),
    ]
