# Generated by Django 5.1.1 on 2024-10-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_emailsetting_status_alter_mailinglog_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsetting',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=50, verbose_name='Статус рассылки'),
        ),
    ]
