# Generated by Django 5.1.1 on 2024-10-08 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_emailsetting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mailing.emailsetting', verbose_name='рассылка'),
        ),
    ]
