# Generated by Django 4.2.2 on 2024-10-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_client_owner_emailsetting_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsetting',
            options={'permissions': [('deactivate_mailing', 'Can deactivate mailing'), ('view_all_mailings', 'Can view all mailings')], 'verbose_name': 'настройка рассылки', 'verbose_name_plural': 'настройки рассылок'},
        ),
    ]
