# Generated by Django 4.2.2 on 2024-10-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_alter_emailsetting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsetting',
            options={'permissions': [('deactivate_mailing', 'Can deactivate mailing')], 'verbose_name': 'настройка рассылки', 'verbose_name_plural': 'настройки рассылок'},
        ),
    ]
